from __future__ import annotations
from typing import Any, Protocol, Literal, Sequence
from typing_extensions import TypeVar, TypeAlias
from collections.abc import Mapping
import builtins

DType: TypeAlias = Any
Device: TypeAlias = Any

class FinfoObject(Protocol):
    '''Floating point type info.
    '''
    @property
    def bits(self) -> int: ...
    @property
    def eps(self) -> Any: ...
    @property
    def max(self) -> Any: ...
    @property
    def min(self) -> Any: ...
    @property
    def smallest_normal(self) -> Any: ...
    @property
    def dtype(self) -> DType: ...

class IinfoObject(Protocol):
    '''Integer type info.
    '''
    @property
    def bits(self) -> int: ...
    @property
    def max(self) -> Any: ...
    @property
    def min(self) -> Any: ...
    @property
    def dtype(self) -> DType: ...

class ArrayNamespaceInfo(Protocol):
    '''Array API namespace introspection information.
    '''
    def capabilities(self) -> Mapping[str, Any]: ...
    def default_device(self) -> Device | None: ...
    def default_dtypes(self, *, device: Device | None = None) -> Mapping[str, DType]: ...
    def devices(self) -> Sequence[Any]: ...
    def dtypes(self, *, device: Device | None = None, kind: Any = None) -> Mapping[str, DType]: ...

class Array(Protocol):
    """Protocol for any backend array type.

    .. note::
        This protocol has been simplified to accomodate Numpy and Jax arrays,
        and should not be taken as a faithful implementation of the Array API
        spec.
    """
    @property
    def dtype(self) -> DType: ...
    @property
    def device(self) -> Device: ...
    @property
    def mT(self) -> Array: ...
    @property
    def ndim(self) -> int: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def size(self) -> int: ...
    @property
    def T(self) -> Array: ...

    def __array_namespace__(self, *, api_version: Any = None) -> Any: ...
    def __getitem__(self, key: Any, /) -> Array: ...
    def __setitem__(self, key: Any, value: Any, /) -> None: ...

    def __abs__(self) -> Array: ...
    def __add__(self, other: Any, /) -> Array: ...
    def __and__(self, other: Any, /) -> Array: ...
    def __bool__(self) -> builtins.bool: ...
    def __complex__(self) -> complex: ...
    # def __dlpack__(self, *, stream: int | Any | None = None, max_version: tuple[int, int] | None = None, dl_device: tuple[Any, int] | None = None, copy: bool | None = None) -> Any: ...
    def __dlpack__(self) -> Any: ...
    # def __dlpack_device__(self) -> tuple[Any, int]: ...
    def __eq__(self, other: Any, /) -> Array: ...  # type: ignore[override]
    def __float__(self) -> float: ...
    def __floordiv__(self, other: Any, /) -> Array: ...
    def __ge__(self, other: Any, /) -> Array: ...
    def __gt__(self, other: Any, /) -> Array: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> Array: ...
    def __le__(self, other: Any, /) -> Array: ...
    def __lshift__(self, other: Any, /) -> Array: ...
    def __lt__(self, other: Any, /) -> Array: ...
    def __matmul__(self, other: Any, /) -> Array: ...
    def __mod__(self, other: Any, /) -> Array: ...
    def __mul__(self, other: Any, /) -> Array: ...
    def __ne__(self, other: Any, /) -> Array: ...  # type: ignore[override]
    def __neg__(self) -> Array: ...
    def __or__(self, other: Any, /) -> Array: ...
    def __pos__(self) -> Array: ...
    def __pow__(self, other: Any, /) -> Array: ...
    def __rshift__(self, other: Any, /) -> Array: ...
    def __sub__(self, other: Any, /) -> Array: ...
    def __truediv__(self, other: Any, /) -> Array: ...
    def __xor__(self, other: Any, /) -> Array: ...

    def __radd__(self, other: Any, /) -> Array: ...
    def __rsub__(self, other: Any, /) -> Array: ...
    def __rmul__(self, other: Any, /) -> Array: ...
    def __rtruediv__(self, other: Any, /) -> Array: ...
    def __rfloordiv__(self, other: Any, /) -> Array: ...
    def __rmod__(self, other: Any, /) -> Array: ...
    def __rpow__(self, other: Any, /) -> Array: ...
    def __rmatmul__(self, other: Any, /) -> Array: ...
    def __rand__(self, other: Any, /) -> Array: ...
    def __ror__(self, other: Any, /) -> Array: ...
    def __rxor__(self, other: Any, /) -> Array: ...
    def __rlshift__(self, other: Any, /) -> Array: ...
    def __rrshift__(self, other: Any, /) -> Array: ...

    def to_device(self, device: Device, /, *, stream: Any = None) -> Array: ...

ArrayT = TypeVar("ArrayT", default=Array)

NormType = Literal['backward', 'ortho', 'forward']

class FFTNamespace(Protocol[ArrayT]):
    '''Protocol for an FFT extension module of an Array API namespace.
    '''
    def fft(self, x: ArrayT, /, *, n: int | None = None, axis: int = -1, norm: NormType = "backward") -> ArrayT: ...
    def ifft(self, x: ArrayT, /, *, n: int | None = None, axis: int = -1, norm: NormType = "backward") -> ArrayT: ...
    def rfft(self, x: ArrayT, /, *, n: int | None = None, axis: int = -1, norm: NormType = "backward") -> ArrayT: ...
    def irfft(self, x: ArrayT, /, *, n: int | None = None, axis: int = -1, norm: NormType = "backward") -> ArrayT: ...
    def hfft(self, x: ArrayT, /, *, n: int | None = None, axis: int = -1, norm: NormType = "backward") -> ArrayT: ...
    def ihfft(self, x: ArrayT, /, *, n: int | None = None, axis: int = -1, norm: NormType = "backward") -> ArrayT: ...
    def fftn(self, x: ArrayT, /, *, s: tuple[int, ...] | None = None, axes: tuple[int, ...] | None = None, norm: NormType = "backward") -> ArrayT: ...
    def ifftn(self, x: ArrayT, /, *, s: tuple[int, ...] | None = None, axes: tuple[int, ...] | None = None, norm: NormType = "backward") -> ArrayT: ...
    def rfftn(self, x: ArrayT, /, *, s: tuple[int, ...] | None = None, axes: tuple[int, ...] | None = None, norm: NormType = "backward") -> ArrayT: ...
    def irfftn(self, x: ArrayT, /, *, s: tuple[int, ...] | None = None, axes: tuple[int, ...] | None = None, norm: NormType = "backward") -> ArrayT: ...
    def fftfreq(self, n: int, /, *, d: float = 1.0, dtype: DType | None = None, device: Device | None = None) -> ArrayT: ...
    def rfftfreq(self, n: int, /, *, d: float = 1.0, dtype: DType | None = None, device: Device | None = None) -> ArrayT: ...
    def fftshift(self, x: ArrayT, /, *, axes: tuple[int, ...] | None = None) -> ArrayT: ...
    def ifftshift(self, x: ArrayT, /, *, axes: tuple[int, ...] | None = None) -> ArrayT: ...

class LinalgNamespace(Protocol[ArrayT]):
    '''Protocol for a Linalg extension module of an Array API namespace.
    '''
    def cholesky(self, x: ArrayT, /, *, upper: builtins.bool = False) -> ArrayT: ...
    def cross(self, x1: ArrayT, x2: ArrayT, /, *, axis: int = -1) -> ArrayT: ...
    def det(self, x: ArrayT, /) -> ArrayT: ...
    def diagonal(self, x: ArrayT, /, *, offset: int = 0) -> ArrayT: ...
    def eig(self, x: ArrayT, /) -> tuple[ArrayT, ArrayT]: ...
    def eigh(self, x: ArrayT, /) -> tuple[ArrayT, ArrayT]: ...
    def eigvals(self, x: ArrayT, /) -> ArrayT: ...
    def eigvalsh(self, x: ArrayT, /) -> ArrayT: ...
    def inv(self, x: ArrayT, /) -> ArrayT: ...
    def matmul(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def matrix_norm(self, x: ArrayT, /, *, keepdims: builtins.bool = False, ord: int | float | Literal['fro', 'nuc'] | None = "fro") -> ArrayT: ...
    def matrix_power(self, x: ArrayT, n: int, /) -> ArrayT: ...
    def matrix_rank(self, x: ArrayT, /, *, rtol: float | None = None) -> ArrayT: ...
    def matrix_transpose(self, x: ArrayT, /) -> ArrayT: ...
    def outer(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def pinv(self, x: ArrayT, /, *, rtol: float | None = None) -> ArrayT: ...
    def qr(self, x: ArrayT, /, *, mode: Literal['reduced', 'complete'] = "reduced") -> tuple[ArrayT, ArrayT]: ...
    def slogdet(self, x: ArrayT, /) -> tuple[ArrayT, ArrayT]: ...
    def solve(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def svd(self, x: ArrayT, /, *, full_matrices: builtins.bool = True) -> tuple[ArrayT, ArrayT, ArrayT]: ...
    def svdvals(self, x: ArrayT, /) -> ArrayT: ...
    def tensordot(self, x1: ArrayT, x2: ArrayT, /, *, axes: int | tuple[Sequence[int], Sequence[int]] = 2) -> ArrayT: ...
    def trace(self, x: ArrayT, /, *, offset: int = 0, dtype: DType | None = None) -> ArrayT: ...
    def vecdot(self, x1: ArrayT, x2: ArrayT, /, *, axis: int = -1) -> ArrayT: ...
    def vector_norm(self, x: ArrayT, /, *, axis: int | tuple[int, ...] | None = None, keepdims: builtins.bool = False, ord: int | float = 2) -> ArrayT: ...

Scalar = bool | int | float | complex

class ArrayNamespace(Protocol[ArrayT]):
    """Protocol for an Array API namespace.
    """
    __array_api_version__: Any
    __name__: str

    # Constants
    pi: float
    e: float
    inf: float
    nan: float
    newaxis: None

    # Type information
    def __array_namespace_info__(self) -> ArrayNamespaceInfo: ...
    def isdtype(self, dtype: DType, kind: DType | str | tuple[DType | str, ...]) -> builtins.bool: ...

    # Dtypes
    bool: DType
    int8: DType
    int16: DType
    int32: DType
    int64: DType
    uint8: DType
    uint16: DType
    uint32: DType
    uint64: DType
    float32: DType
    float64: DType
    complex64: DType
    complex128: DType

    # Creation
    def asarray(self, obj: ArrayT | builtins.bool | int | float | complex, /, *, dtype: DType | None = None, device: Device | None = None, copy: builtins.bool | None = None) -> ArrayT: ...
    def zeros(self, shape: int | tuple[int, ...], *, dtype: DType | None = None, device: Device | None = None) -> ArrayT: ...
    def ones(self, shape: int | tuple[int, ...], *, dtype: DType | None = None, device: Device | None = None) -> ArrayT: ...
    def empty(self, shape: int | tuple[int, ...], *, dtype: DType | None = None, device: Device | None = None) -> ArrayT: ...
    def full(self, shape: int | tuple[int, ...], fill_value: Scalar, *, dtype: DType | None = None, device: Device | None = None) -> ArrayT: ...
    def arange(self, start: int | float, /, stop: int | float | None = None, step: int | float = 1, *, dtype: DType | None = None, device: Device | None = None) -> ArrayT: ...
    def linspace(self, start: int | float | complex, stop: int | float | complex, /, num: int, *, dtype: DType | None = None, device: Device | None = None, endpoint: builtins.bool = True) -> ArrayT: ...
    def eye(self, n_rows: int, n_cols: int | None = None, /, *, k: int = 0, dtype: DType | None = None, device: Device | None = None) -> ArrayT: ...
    def zeros_like(self, x: ArrayT, /, *, dtype: DType | None = None, device: Device | None = None) -> ArrayT: ...
    def ones_like(self, x: ArrayT, /, *, dtype: DType | None = None, device: Device | None = None) -> ArrayT: ...
    def empty_like(self, x: ArrayT, /, *, dtype: DType | None = None, device: Device | None = None) -> ArrayT: ...
    def full_like(self, x: ArrayT, /, fill_value: Scalar, *, dtype: DType | None = None, device: Device | None = None) -> ArrayT: ...
    def from_dlpack(self, x: Any, /, *, device: Device | None = None, copy: builtins.bool | None = None) -> ArrayT: ...
    def meshgrid(self, *arrays: ArrayT, indexing: Literal['xy', 'ij'] = 'xy') -> Sequence[ArrayT]: ...
    def tril(self, x: ArrayT, /, *, k: int = 0) -> ArrayT: ...
    def triu(self, x: ArrayT, /, *, k: int = 0) -> ArrayT: ...

    # Manipulation
    def reshape(self, x: ArrayT, /, shape: tuple[int, ...], *, copy: builtins.bool | None = None) -> ArrayT: ...
    def squeeze(self, x: ArrayT, /, axis: int | tuple[int, ...]) -> ArrayT: ...
    def expand_dims(self, x: ArrayT, /, axis: int | tuple[int, ...]) -> ArrayT: ...
    def flip(self, x: ArrayT, /, *, axis: int | tuple[int, ...] | None = None) -> ArrayT: ...
    def permute_dims(self, x: ArrayT, /, axes: tuple[int, ...]) -> ArrayT: ...
    def concat(self, arrays: tuple[ArrayT, ...] | list[ArrayT], /, *, axis: int = 0) -> ArrayT: ...
    def stack(self, arrays: tuple[ArrayT, ...] | list[ArrayT], /, *, axis: int = 0) -> ArrayT: ...
    def broadcast_to(self, x: ArrayT, /, shape: tuple[int, ...]) -> ArrayT: ...
    def broadcast_arrays(self, *arrays: ArrayT) -> Sequence[ArrayT]: ...
    def broadcast_shapes(self, *shapes: tuple[int, ...]) -> tuple[int, ...]: ...
    def moveaxis(self, x: ArrayT, source: int | tuple[int, ...], destination: int | tuple[int, ...], /) -> ArrayT: ...
    def repeat(self, x: ArrayT, repeats: Any, /, *, axis: int | None = None) -> ArrayT: ...
    def roll(self, x: ArrayT, /, shift: int | tuple[int, ...], *, axis: int | tuple[int, ...] | None = None) -> ArrayT: ...
    def tile(self, x: ArrayT, repetitions: tuple[int, ...], /) -> ArrayT: ...
    def unstack(self, x: ArrayT, /, *, axis: int = 0) -> tuple[ArrayT, ...]: ...

    # Sorting / searching
    def sort(self, x: ArrayT, /, *, axis: int = -1, descending: builtins.bool = False, stable: builtins.bool = True) -> ArrayT: ...
    def argsort(self, x: ArrayT, /, *, axis: int = -1, descending: builtins.bool = False, stable: builtins.bool = True) -> ArrayT: ...
    def nonzero(self, x: ArrayT, /) -> tuple[ArrayT, ...]: ...
    def where(self, condition: ArrayT, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def searchsorted(self, x1: ArrayT, x2: ArrayT | int | float, /, *, side: Literal['left', 'right'] = "left", sorter: ArrayT | None = None) -> ArrayT: ...
    def argmax(self, x: ArrayT, /, *, axis: int | None = None, keepdims: builtins.bool = False) -> ArrayT: ...
    def argmin(self, x: ArrayT, /, *, axis: int | None = None, keepdims: builtins.bool = False) -> ArrayT: ...
    def count_nonzero(self, x: ArrayT, /, *, axis: int | None = None, keepdims: builtins.bool = False) -> ArrayT: ...

    # Reductions
    def all(self, x: ArrayT, /, *, axis: int | tuple[int, ...] | None = None, keepdims: builtins.bool = False) -> ArrayT: ...
    def any(self, x: ArrayT, /, *, axis: int | tuple[int, ...] | None = None, keepdims: builtins.bool = False) -> ArrayT: ...
    def max(self, x: ArrayT, /, *, axis: int | tuple[int, ...] | None = None, keepdims: builtins.bool = False) -> ArrayT: ...
    def min(self, x: ArrayT, /, *, axis: int | tuple[int, ...] | None = None, keepdims: builtins.bool = False) -> ArrayT: ...
    def sum(self, x: ArrayT, /, *, axis: int | tuple[int, ...] | None = None, dtype: DType | None = None, keepdims: builtins.bool = False) -> ArrayT: ...
    def mean(self, x: ArrayT, /, *, axis: int | tuple[int, ...] | None = None, keepdims: builtins.bool = False) -> ArrayT: ...
    def std(self, x: ArrayT, /, *, axis: int | tuple[int, ...] | None = None, correction: float = 0.0, keepdims: builtins.bool = False) -> ArrayT: ...
    def var(self, x: ArrayT, /, *, axis: int | tuple[int, ...] | None = None, correction: float = 0.0, keepdims: builtins.bool = False) -> ArrayT: ...
    def prod(self, x: ArrayT, /, *, axis: int | tuple[int, ...] | None = None, dtype: DType | None = None, keepdims: builtins.bool = False) -> ArrayT: ...
    def cumulative_prod(self, x: ArrayT, /, *, axis: int | None = None, dtype: DType | None = None, include_initial: builtins.bool = False) -> ArrayT: ...
    def cumulative_sum(self, x: ArrayT, /, *, axis: int | None = None, dtype: DType | None = None, include_initial: builtins.bool = False) -> ArrayT: ...

    # Linear algebra (core spec, not extension)
    def matmul(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def matrix_transpose(self, x: ArrayT, /) -> ArrayT: ...
    def tensordot(self, x1: ArrayT, x2: ArrayT, /, *, axes: int | tuple[Sequence[int], Sequence[int]] = 2) -> ArrayT: ...
    def vecdot(self, x1: ArrayT, x2: ArrayT, /, *, axis: int = -1) -> ArrayT: ...

    # Element-wise math
    def abs(self, x: ArrayT, /) -> ArrayT: ...
    def acos(self, x: ArrayT, /) -> ArrayT: ...
    def acosh(self, x: ArrayT, /) -> ArrayT: ...
    def asin(self, x: ArrayT, /) -> ArrayT: ...
    def asinh(self, x: ArrayT, /) -> ArrayT: ...
    def atan(self, x: ArrayT, /) -> ArrayT: ...
    def atanh(self, x: ArrayT, /) -> ArrayT: ...
    def atan2(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def ceil(self, x: ArrayT, /) -> ArrayT: ...
    def clip(self, x: ArrayT, /, min: int | float | ArrayT | None = None, max: int | float | ArrayT | None = None) -> ArrayT: ...
    def conj(self, x: ArrayT, /) -> ArrayT: ...
    def copysign(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def cos(self, x: ArrayT, /) -> ArrayT: ...
    def cosh(self, x: ArrayT, /) -> ArrayT: ...
    def divide(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def exp(self, x: ArrayT, /) -> ArrayT: ...
    def expm1(self, x: ArrayT, /) -> ArrayT: ...
    def floor(self, x: ArrayT, /) -> ArrayT: ...
    def floor_divide(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def hypot(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def imag(self, x: ArrayT, /) -> ArrayT: ...
    def isfinite(self, x: ArrayT, /) -> ArrayT: ...
    def isinf(self, x: ArrayT, /) -> ArrayT: ...
    def isnan(self, x: ArrayT, /) -> ArrayT: ...
    def log(self, x: ArrayT, /) -> ArrayT: ...
    def log1p(self, x: ArrayT, /) -> ArrayT: ...
    def log2(self, x: ArrayT, /) -> ArrayT: ...
    def log10(self, x: ArrayT, /) -> ArrayT: ...
    def logaddexp(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def maximum(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def minimum(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def multiply(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def negative(self, x: ArrayT, /) -> ArrayT: ...
    def nextafter(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def positive(self, x: ArrayT, /) -> ArrayT: ...
    def pow(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def real(self, x: ArrayT, /) -> ArrayT: ...
    def reciprocal(self, x: ArrayT, /) -> ArrayT: ...
    def remainder(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def round(self, x: ArrayT, /) -> ArrayT: ...
    def sign(self, x: ArrayT, /) -> ArrayT: ...
    def signbit(self, x: ArrayT, /) -> ArrayT: ...
    def sin(self, x: ArrayT, /) -> ArrayT: ...
    def sinh(self, x: ArrayT, /) -> ArrayT: ...
    def sqrt(self, x: ArrayT, /) -> ArrayT: ...
    def square(self, x: ArrayT, /) -> ArrayT: ...
    def subtract(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def tan(self, x: ArrayT, /) -> ArrayT: ...
    def tanh(self, x: ArrayT, /) -> ArrayT: ...
    def trunc(self, x: ArrayT, /) -> ArrayT: ...

    # Comparison
    def equal(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def greater(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def greater_equal(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def less(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def less_equal(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def not_equal(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...

    # Bitwise
    def bitwise_and(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def bitwise_invert(self, x: ArrayT, /) -> ArrayT: ...
    def bitwise_left_shift(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def bitwise_or(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def bitwise_right_shift(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def bitwise_xor(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...

    # Logical
    def logical_and(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def logical_not(self, x: ArrayT, /) -> ArrayT: ...
    def logical_or(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...
    def logical_xor(self, x1: ArrayT, x2: ArrayT, /) -> ArrayT: ...

    # Type utilities
    def astype(self, x: ArrayT, dtype: DType, /, *, copy: builtins.bool = True, device: Device | None = None) -> ArrayT: ...
    def result_type(self, *arrays_and_dtypes: ArrayT | DType | int | float | complex | builtins.bool) -> DType: ...
    def can_cast(self, from_: DType | ArrayT, to: DType, /) -> builtins.bool: ...
    def finfo(self, type: DType | ArrayT, /) -> FinfoObject: ...
    def iinfo(self, type: DType | ArrayT, /) -> IinfoObject: ...

    # Utility
    def diff(self, x: ArrayT, /, *, axis: int = -1, n: int = 1, prepend: Any = None, append: Any = None) -> ArrayT: ...

    # Set
    def isin(self, x1: ArrayT, x2: ArrayT, /, *, invert: builtins.bool = False) -> ArrayT: ...
    def unique_all(self, x: ArrayT, /) -> tuple[ArrayT, ArrayT, ArrayT, ArrayT]: ...
    def unique_counts(self, x: ArrayT, /) -> tuple[ArrayT, ArrayT]: ...
    def unique_inverse(self, x: ArrayT, /) -> tuple[ArrayT, ArrayT]: ...
    def unique_values(self, x: ArrayT, /) -> ArrayT: ...

    # Indexing
    def take(self, x: ArrayT, indices: ArrayT, /, *, axis: int | None = None) -> ArrayT: ...
    def take_along_axis(self, x: ArrayT, indices: ArrayT, /, *, axis: int = -1) -> ArrayT: ...

    # Sub-namespaces (optional, checked via hasattr at runtime)
    fft: FFTNamespace[ArrayT]
    linalg: LinalgNamespace[ArrayT]
