name: Array API

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  pytest:
    name: Compliance
    runs-on: ubuntu-latest

    steps:
    - name: Check out hcipy repo
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        filter: tree:0

    - name: Checkout array-api-tests repo
      uses: actions/checkout@v6
      with:
        repository: data-apis/array-api-tests
        submodules: 'true'
        path: array-api-tests

    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: ci-env
        python-version: "3.14"
        environment-file: ./.github/conda_environments/testing_env.yml
        auto-activate-base: false

    - name: Install optional dependencies if available
      run: |
        while read requirement; do
          conda install --yes $requirement || true
        done < ./.github/conda_environments/optional_dependencies.txt
      shell: bash -l {0}

    - name: Install our package
      run: |
        pip install -e ".[dev]"
      shell: bash -l {0}

    - name: Install array-api-tests dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install array-api-strict
        python -m pip install -r array-api-tests/requirements.txt
      shell: bash -l {0}

    - name: Print package versions
      run: |
        python --version
        python -c "import numpy; print('Numpy', numpy.__version__)"
        python -c "import scipy; print('Scipy', scipy.__version__)"
        python -c "import matplotlib; print('Matplotlib', matplotlib.__version__)"
        python -c "import hcipy; print('HCIPy', hcipy.__version__)"
        conda list
      shell: bash -l {0}

    - name: Run the array_api test suite
      env:
        ARRAY_API_TESTS_MODULE: "exec('import hcipy; import array_api_strict; xp = hcipy.make_field_namespace(array_api_strict)')"
        ARRAY_API_STRICT_API_VERSION: 2024.12
      run: |
        pytest ./array-api-tests/ -ra -v --cov=./ --cov-report=xml --skips-file ./.github/workflows/array-api-tests-skips.txt
      shell: bash -l {0}

    - name: Upload coverage to codecov.io
      if: always()
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
