name: Testing JAX

on:
  pull_request:
    branches:
      - master


jobs:
  pytest:
    name: Pytest (${{ matrix.os }} Python${{ matrix.python_version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python_version: ["3.12"]

    steps:
    - name: Check out repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: tree:0
    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: ci-env
        python-version: ${{ matrix.python_version }}
        environment-file: .github/conda_environments/testing_env.yml
        auto-activate-base: false
    - name: Install optional dependencies if available
      run: |
        while read requirement; do
          conda install --yes $requirement || true
        done < .github/conda_environments/optional_dependencies.txt
      shell: bash -l {0}
    - name: Change default backend to JAX
      run: |
        sed -i "s/default_backend: 'numpy'/default_backend: 'jax.numpy'/" hcipy/config/default_config.yaml
      shell: bash -l {0}
    - name: Install our package
      run: |
        pip install -e ".[dev]"
      shell: bash -l {0}
    - name: Print package versions
      run: |
        python --version
        python -c "import numpy; print('Numpy', numpy.__version__)"
        python -c "import scipy; print('Scipy', scipy.__version__)"
        python -c "import matplotlib; print('Matplotlib', matplotlib.__version__)"
        python -c "import hcipy; print('HCIPy', hcipy.__version__)"
        conda list
      shell: bash -l {0}
    - name: Run tests
      run: |
        pytest ./tests -ra 
      shell: bash -l {0}
   
